version: '3'

services:
  mysqldb:
    container_name: mysql8
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testing
  fullstack:
    container_name: app
    depends_on:
      - mysqldb
    image: al3zama/springboot-react:latest
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql8:3306/testing"
      }'